# Generated by Django 5.0 on 2025-09-16 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="is_reported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="report_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True, related_name="reported_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
